package:
  name: fsttrpgcharacterloader
  version: 0.1.9

build:
 number: 4
 string: alpha

source:
  git_url: https://github.com/Krypticdator/FSTTRPGCharacterLoader.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
about:
  summary: Fuzion Roleplayin System characterloader